---
title: Resume
format: html
---

## 🎓 Education

**Bachelor of Business \| Accounting**\
*Queensland University of Technology (QUT), Brisbane*\
Jul 2024 – Jul 2026 \| International Merit Scholarship

-   *Courses*: Financial Accounting, Management Accounting, Company Accounting, Taxation, Audit & Assurance, Business Law, Corporations Law, Business Analytics, Fundamentals of Finance.

-   *Achievements & Extra-curriculars*:

    -   4x Executive Dean’s Commendation for Academic Excellence

    -   Achievement Award in *AYB106 Accounting Processes and Systems* for the 2024 academic year

    -   QUT College of Excellence Member

    -   QUT Buddhism Society - Treasurer

    -   QUT Accountancy Student Association (QUTASA) - Vice President\

**Cert. III, IV & Diploma \| Accounting & Bookkeeping**\
*TAFE Queensland, Brisbane*\
Feb 2023 – Jun 2024

-   *BAS Agent Skillset*: BAS, IAS, PAYG Withholding, PAYG Instalments, Payroll, FBT, LCT, FTC, WET.

-   *Accounting Principles*: Financial & Company Accounting, Management Accounting, Budgeting & Forecasting, Income Tax Returns for Individuals, XERO Software, HandiTax Software, Excel Spreadsheet.

-   *Achievements*: Graduate of the Year 2023 & 2024 Double Award

**Advanced Federal Diploma \| Hospitality Management**\
*VATEL Switzerland*\
Aug 2018 – Mar 2021

-   *Courses*: Marketing, Financial Management & Cost Control, Human Resources, IT, Tourism Economics, Swiss Taxation, Hospitality Sales, Multicultural Management, Mandarin, Spanish.

-   *Alternate Weeks*: Front Office, Housekeeping, Restaurant, Bar, Banqueting, Kitchen, Pastry, F&B control

-   *2 Internships*: domestic (Switzerland) and international (Vietnam)

-   *Achievements*: Triple Awards for Best Student in Swiss Taxation, Human Resources & Capstone Business Project (in charge of Finance)

------------------------------------------------------------------------

## 📂 Certifications

-   Grant Thornton Audit Simulation on Forage
-   KPMG Data Analytics Job Simulation on Forage
-   Google Data Analytics Certificate
-   Xero Advisor & Payroll Certified

------------------------------------------------------------------------

## 👨‍💼 Professional Experience

**Business Advisory Intern – Vincents, Brisbane**\
Nov – Dec 2025

Under QUT's Work-Integrated Learning Program, I gained hands-on exposure in preparing:

-   Income Tax Returns for Individuals, Trusts, Companies and Partnerships
-   Business Activity Statements and Instalment Activity Statements
-   Special Purpose Financial Statements
-   Workpapers to a quality standard set by the Division
-   Alignment Journals and other adjustments

**Bookkeeping Intern – Link Advisors, Brisbane**\
Jan – Apr 2024

-   Performed A/P and A/R reconciliations, ensuring accurate supplier and customer balances
-   Managed automation rules in Dext and Hubdoc to streamline document capture and coding
-   Supported BAS and IAS reconciliation and lodgement processes
-   Assisted with payroll duties, including timesheet review, data entry, and payroll reconciliation

**Tutor – Lingua Franca School, Brisbane**\
Jun 2023 – Apr 2024

-   Delivered private and group French lessons to adult learners, from Beginner to Advanced levels.
-   Tutored students preparing for the DELF exam.
-   Created and reviewed course materials.

**Front Office All-Rounder – Marriott Hotel, Brisbane**\
Aug – Oct 2022\
-Working Holiday Visa-

-   Performed check-ins and check-outs as per Marriott standards of procedures.
-   Addressed customer inquiries over the switchboard and liaised with other departments.
-   Prepared VIP amenities prior to guest arrival.

**Finance Trainee – Sofitel Saigon Plaza, Vietnam**\
May – Jul 2022

-   Administered credit control over 40 accounts receivable daily.
-   Arranged payment plan with creditors to optimise collection.
-   Reconciled credit card and general ledgers.
-   Collaborated with operations and sales team to ensure accurate records and follow-up.
-   Posted financial data in ledgers on Opera PMS and raised e-invoices on the government tax system.
-   Prepared credit meetings.
-   Ensured proper financial record classification as per Accor standards.

**F&B Management Trainee – Sofitel Saigon Plaza, Vietnam**\
Feb – Jul 2020

-   Coordinated reopening project of the Hotel’s gastronomic restaurant.
-   Implemented rebranding as “Bistro le 17”; presented project to management and owner.
-   Created new menu, food and beverage costing and pricing.
-   Conducted competitor survey and analysis.
-   Created and conducted staff training.

**F&B Intern – President Wilson Hotel, Switzerland**\
Feb – Jul 2020

-   Provided high-class service for “Bayview” restaurant (1\* Michelin, 17/20 Gault&Millau).
-   Delivered VIP services as a Room service attendant for the Presidential Suite.

**Professional Placement – Vatel Hotel, Switzerland**\
2018 – 2021 (Casual)

-   Operations across all the Hotel's Departments, shift leader for junior students.

------------------------------------------------------------------------

## 🙌 Volunteering

**Vice-President – QUT ASA (Nov 2024–Now)**

-   Strengthening and expanding partnerships with 15+ corporate sponsors, ensuring long-term engagement and value for both sides

-   Working closely with the executive team to proactively resolve enquiries and maintain strong stakeholder satisfaction

-   Managing event operations and leading the promotion of the Society's events, boosting visibility and participation across the QUT community

-   Overseeing digital workspaces by designing and implementing workflow systems that improve team productivity

-   Providing strategic leadership to guide the club’s direction, culture, and long-term growth

**AMEP Tutor – TAFE Brisbane (Feb–May 2023)**

-   Provided in-class education support for humanitarian migrants in ESL language development.

-   Interpreted role-plays to assist NAATI students in simulated tests.

**Cash Register Operator – Lifeline Bookfest (Jan 2023)**

-   Supported cashier duties & customer service at the Bookfest held in Brisbane.\

------------------------------------------------------------------------

## 📬 References

Chris Tinta, Director, LINK ACCOUNTING\
[chris\@link.com.au](mailto:chris@link.com.au)

David Marley, Leading Teacher, TAFE Qld\
[david.marley\@tafeqld.edu.au](mailto:david.marley@tafeqld.edu.au)

------------------------------------------------------------------------
